### ISSUE TITLE
Page crash after attempt to generate config/QR for user with no permission

### ISSUE THREAD

**Issue by almulalic** [DefGuard/defguard#587]
**Describe the bug**
Page crash after attempt to generate config/QR for user with no permission for that network.

**To Reproduce**
1. Go to location settings
2. Assign a group that some user, eg 'User1', doesen't belog to, eg 'Admin'
3. Make sure that 'User1' is not in group 'Admin'
4. Log in as 'User1'
5. Attempt to add device
6. Form should crash at the end due to some JS issues

**Expected behavior**
User should be redirected to some kind of 403 page.

**Version information**
- Defguard Core version: latest
  - Operating system and version running the gateway:  Centos, Linux 6.1.6-1.el8.elrepo.x86_64, k8s
-- | --

**Screenshots**

**Additiona
<img width="1688" alt="Screenshot 2024-03-15 at 13 51 54" src="https://github.com/DefGuard/defguard/assets/47641522/6264391c-4e5d-48a3-8be5-d5789154e537">

**Comment by teon** [comment]
@almulalic could you share any details about the configuration so we could replicate/try to. find what's wrong? If you don't want to post them here publicly you can email us at: support@defguard.net.
We need:
- name of the VPN
- name of the device
- first, ast name & username of the user for which the device was configured
- VPN server IP
-  port
- VPN network address

Also can you go to the "core" logs and post them?

Based on that we will replicate and have the ability to fix.

**Comment by almulalic** [comment]
Sure, I can publish it here. I managed to get a video for this which I sent to support email.
Most of the questions are answered in the video, however I can't share the IP and port.

However I could share my deployment info:
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defguard
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defguard
  template:
    metadata:
      labels:
        app: defguard
    spec:
      containers:
        - name: core
          image: ghcr.io/defguard/defguard:sha-db61513
          envFrom:
            - secretRef:
                name: defguard-secret
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 50055
              protocol: TCP
          volumeMounts:
            - name: ssl-certs
              mountPath: /ssl
        - name: proxy
          image: ghcr.io/defguard/defguard-proxy:latest
          envFrom:
            - secretRef:
                name: defguard-secret
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50052
              protocol: TCP
          volumeMounts:
            - name: ssl-certs
              mountPath: /ssl
      volumes:
        - name: ssl-certs
          hostPath:
            path: /opt/defguard/ssl

---
apiVersion: v1
kind: Service
metadata:
  name: defguard-tcp
  namespace: infra
spec:
  selector:
    app: defguard
  ports:
    - name: defguard-grpc
      protocol: TCP
      port: 50055
      targetPort: 50055
    - name: defguard-proxy
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: defguard-main-ui
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: defguard-enroll-ui
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: defguard-udp
  namespace: infra
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: defguard
  ports:
    - protocol: UDP
      port: 50051
      targetPort: 50051
      name: wireguard-def

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: defguard-grpc
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grpc.defguard.tuxhub.cloud`)
      kind: Rule
      services:
        - name: defguard-tcp
          port: 50055

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: defguard-main-ui
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`defguard.tuxhub.cloud`)
      kind: Rule
      services:
        - name: defguard-tcp
          port: 8000

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: defguard-proxy
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`proxy.defguard.tuxhub.cloud`)
      kind: Rule
      services:
        - name: defguard-tcp
          port: 50052

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: defguard-enroll-ui
  namespace: infra
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`enroll.defguard.tuxhub.cloud`)
      kind: Rule
      services:
        - name: defguard-tcp
          port: 8080

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: defguard-wireguard
  namespace: infra
spec:
  entryPoints:
    - wireguard-def
  routes:
    - services:
      - name: wireguard-defguard
        port: 50051
        weight: 9
        nativeLB: true
```

gateway
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defguard-homeserver-gateway
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defguard-homeserver-gateway
  template:
    metadata:
      labels:
        app: defguard-homeserver-gateway
    spec:
      containers:
        - name: gateway
          image: ghcr.io/defguard/gateway:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 50051
              protocol: UDP
          envFrom:
            - secretRef:
                name: defguard-homeserver-gateway-secret
          volumeMounts:
            - name: ssl-certs
              mountPath: /ssl
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.98.6
          - 8.8.8.8
      volumes:
        - name: ssl-certs
          hostPath:
            path: /opt/defguard/ssl

---
apiVersion: v1
kind: Service
metadata:
  name: defguard-homeserver-gateway
  namespace: infra
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: defguard-homeserver-gateway
  ports:
    - protocol: UDP
      port: 50051
      targetPort: 50051
      name: wireguard-def

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: defguard-homeserver-gateway
  namespace: infra
spec:
  entryPoints:
    - wireguard-def
  routes:
    - services:
      - name: defguard-homeserver-gateway
        port: 50051
        weight: 9
        nativeLB: true
```

.env
```
# Databse
DEFGUARD_DB_HOST=postgresql.data.svc.cluster.local
DEFGUARD_DB_PORT=5432
DEFGUARD_DB_USER=defguard
DEFGUARD_DB_PASSWORD=X
DEFGUARD_DB_NAME=defguard

# Core
DEFGUARD_LOG_LEVEL=DEBUG
DEFGUARD_AUTH_SECRET=X
DEFGUARD_YUBIBRIDGE_SECRET=X
DEFGUARD_GATEWAY_SECRET=X
DEFGUARD_SECRET_KEY=X
DEFGUARD_URL=https://defguard.tuxhub.cloud
DEFGUARD_WEBAUTHN_RP_ID=defguard.tuxhub.cloud
DEFGUARD_COOKIE_INSECURE=false
DEFGUARD_ENROLLMENT_URL=https://enroll.defguard.tuxhub.cloud
DEFGUARD_PROXY_URL=http://defguard-tcp.infra.svc.cluster.local:50052
DEFGUARD_DEFAULT_ADMIN_PASSWORD=X

# Proxy
DEFGUARD_PROXY_GRPC_PORT=50052
DEFGUARD_PROXY_HTTP_PORT=8080
```

gateway .env
```
DEFGUARD_GRPC_URL=http://defguard-tcp.infra.svc.cluster.local:50055
DEFGUARD_STATS_PERIOD=30
DEFGUARD_TOKEN=X
POSTUP=iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
POSTDOWN=iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
```
