### ISSUE TITLE
Cannot setup iptables

### ISSUE THREAD

**Issue by amanzone** [DefGuard/defguard#823]
I start the gateway with docker compose:

```
  gateway: 
    image: ghcr.io/defguard/gateway:${GATEWAY_IMAGE_TAG:-latest} 
    command: ["-i", "wg1"]
    restart: unless-stopped
    network_mode: "host"
#    user: 1001:1001
    environment: 
      DEFGUARD_GRPC_URL: https://defguard.home.com:50055
      DEFGUARD_GRPC_CA: /ssl/defguard-ca.pem 
      DEFGUARD_STATS_PERIOD: 30 
      DEFGUARD_TOKEN: ${DEFGUARD_TOKEN} 
      POST_UP: iptables -t nat -A POSTROUTING -s 10.11.0.0/24 -o enp0s3 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 33003 -j ACCEPT; iptables -A FORWARD -i wg1 -j ACCEPT; iptables -A FORWARD -o wg1 -j ACCEPT;
      POST_DOWN: iptables -t nat -D POSTROUTING -s 10.11.0.0/24 -o enp0s3 -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport 33003 -j ACCEPT; iptables -D FORWARD -i wg1 -j ACCEPT; iptables -D FORWARD -o wg1 -j ACCEPT;
    ports:
      # wireguard port
      - "33003:33003"    
    volumes: 
  # SSL setup guide: https://defguard.gitbook.io/defguard/features/setting-up-your-instance/docker-compose#ssl-setup
      - ${VOLUME_DIR:-./.volumes}/ssl:/ssl 
    cap_add:
      - NET_ADMIN
```

This generates an error in the gateway log due to the fact that iptables is not installed in the container.
Of course I can remove the POST_UP environment variable, so the container starts fine, but I do not have rules set...
